### ISSUE TITLE
Update icons for the guide/playbook

### ISSUE THREAD

**Issue by mgifford** [CivicActions/accessibility#106]
The guidebook icons need to be updated for history & glossary - https://accessibility.civicactions.com/guide

Right now they are duplicated. 

## To-do

- [x] add code to pull font awesome icons for playbook/guide
- [ ] add icons to playbook (this file: https://github.com/CivicActions/accessibility/blob/main/_data/playbook.yml)
- [ ] clean up code in meta to correctly pull font awesome CDN code (see comments: https://github.com/CivicActions/accessibility/blob/main/_includes/meta.html#L14)

**Comment by lukefretwell** [comment]
@mgifford I updated the code to pull font awesome icons. Created a checklist above.
