### ISSUE TITLE
Retrospective: March 25, 2021

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#182]
## To-do:

- [x] Set up board (copy all columns from previous board - [ex](https://github.com/CivicActions/accessibility/projects/3))
- [x] Add new team members to CivicActions GitHub team 
- [x] Announce to #accessibility channel one week before (see sample text below)
- [x] Announce to #accessibility channel day of (see sample text below)
- [x] Hold retrospective
- [x] Post final retrospective to #accessibility channel

Sample text:

> Hello @channel, next week is our practice area’s retrospective: [DAY], [MONTH] [DATE], [TIME] pm to [TIME] pm PT ([TIME] pm to [TIME] pm ET). We welcome you to attend and you can use this link to add the event and Zoom link to your calendar.

> The retrospective board is available here [LINK] and please feel free to add notes to the different columns between now and then.

> If you have trouble adding the event and adding notes to that board let us know and we will get you added to the calendar event and :ca: GitHub team. Also if you have any questions please post them in the channel. Thank you!
