### ISSUE TITLE
Retrospective: June 21-24 2021

### ISSUE THREAD

**Issue by dmundra** [CivicActions/accessibility#406]
## To-do:

- [x] Set up board (copy all columns from previous board - [ex](https://github.com/CivicActions/accessibility/projects/3))
- [x] Add new team members to CivicActions GitHub team 
- [x] Day 1 Monday, June 21st, prompt in slack the retrospective questions and asks folks to enter them at their own pace throughout the day.
- [x] Day 2/3 Tuesday, June 22nd, summarize and consolidates common points on the board. Then provide multiple polls to vote on the items from each column. Prompt in slack with a link to each poll.
- [x] Day 4 Thursday, June 24th, asks for action items for the most voted items from the poll.
- [x] Day 5 Friday, June 25th, create backlog issues, share the results, and close the retrospective.

Sample texts:

Day 1:
> Hello @channel, this week is the accessibility practice area's quarterly retrospective. Please go ahead and take some time **today** to fill out the columns in our [retrospective board](https://github.com/CivicActions/accessibility/projects/4). Add project milestones that have occurred since the [last retrospective (March 25th)](https://github.com/CivicActions/accessibility/projects/3). Add thoughts (as notes) to each column "LOVED," "LONGED FOR," "LOATHED" and "LEARNED."

> If you have trouble adding notes to that board let us know and we will get you added to the :ca: GitHub team. Also if you have any questions please post them in the channel. Thank you!

Day 2/3:
> Hello @channel, thank you for adding items to the [retrospective board](https://github.com/CivicActions/accessibility/projects/4). Please follow the links to a poll for each column to vote on the different items (common ones have been combined):

Day 4:
> Hello @channel, thank you for voting on the retrospective items. Here are the top-voted items. Please comment/discuss on this slack thread action items for the ones you want to amplify, remove, and/or continue doing. I will create backlog issues when we form items we want to pursue:

Day 5:
> Hello @channel, retrospective #_ is done. Link: https://github.com/CivicActions/accessibility/projects/4. The following issues are action items that are in the main project backlog:

**Comment by dmundra** [comment]
Is #178 still a concern/unanswered? Bring to this retrospective.

**Comment by dmundra** [comment]
New board: https://github.com/CivicActions/accessibility/projects/4

**Comment by dmundra** [comment]
Maybe next retrospective fully in slack?
