### ISSUE TITLE
Set up sprint planning + check-in times

### ISSUE THREAD

**Issue by lukefretwell** [CivicActions/accessibility#47]
We're going to set up a 30-minute weekly (Mon.) sprint planning call and twice-weekly (Tues./Thurs.) 15-minute scrum.

Anyone interested in joining either of these?

## To-do

- [x] Ask team members if they'd like to join
- [x] Add to CivicActions Accessibility calendar / invite team members
- [x] Tie notification into Slack
